<?php

$env = "prod";
if($env == "local"){
  define('HTTP_SERVER', 'http://localhost');
  define('HTTPS_SERVER', 'http://localhost');
  define('ENABLE_SSL', false);
  define('HTTP_COOKIE_DOMAIN', '');
  define('HTTPS_COOKIE_DOMAIN', '');
  define('HTTP_COOKIE_PATH', '/stores/AshokProvision/admin');
  define('HTTPS_COOKIE_PATH', '/stores/AshokProvision/admin');
  define('HTTP_CATALOG_SERVER', 'http://localhost');
  define('HTTPS_CATALOG_SERVER', 'http://localhost');
  define('ENABLE_SSL_CATALOG', 'false');
  define('DIR_FS_DOCUMENT_ROOT', '/opt/lampp/htdocs/stores/AshokProvision/');
  define('DIR_WS_ADMIN', '/stores/AshokProvision/admin/');
  define('DIR_WS_HTTPS_ADMIN', 'stores/AshokProvision/admin/');
  define('DIR_FS_ADMIN', '/opt/lampp/htdocs/stores/AshokProvision/admin/');
  define('DIR_WS_CATALOG', '/FieldMitr_B2C_OrderBooking/');
  define('DIR_WS_HTTPS_CATALOG', '/FieldMitr_B2C_OrderBooking/');
  define('DIR_FS_CATALOG', '/opt/lampp/htdocs/stores/AshokProvision/');
  define('DIR_WS_CATALOG_IMAGES', DIR_WS_CATALOG . 'images/');
  define('DIR_WS_CATALOG_LANGUAGES', DIR_WS_CATALOG . 'includes/languages/');
  define('DIR_FS_CATALOG_LANGUAGES', DIR_FS_CATALOG . 'includes/languages/');
  define('DIR_FS_CATALOG_IMAGES', DIR_FS_CATALOG . 'images/');
  define('DIR_FS_CATALOG_MODULES', DIR_FS_CATALOG . 'includes/modules/');
  define('DIR_FS_BACKUP', DIR_FS_ADMIN . 'backups/');
  define('DIR_FS_DOWNLOAD', DIR_FS_CATALOG . 'download/');
  define('DIR_FS_DOWNLOAD_PUBLIC', DIR_FS_CATALOG . 'pub/');
  define('DB_SERVER', '127.0.0.1');
  define('DB_SERVER_USERNAME', 'root');
  define('DB_SERVER_PASSWORD', 'root');
  define('DB_DATABASE', 'AshokProvision');
  define('USE_PCONNECT', 'false');
  define('STORE_SESSIONS', 'mysql');
  define('CFG_TIME_ZONE', 'Asia/Kolkata');
}else if($env == "prod"){
   define('HTTP_SERVER', 'shorturl.at/enrC3');
  define('HTTPS_SERVER', 'shorturl.at/enrC3');
  define('ENABLE_SSL', false);
  define('HTTP_COOKIE_DOMAIN', '');
  define('HTTPS_COOKIE_DOMAIN', '');
  define('HTTP_COOKIE_PATH', '/stores/AshokProvision/admin');
  define('HTTPS_COOKIE_PATH', '/stores/AshokProvision/admin');
  define('HTTP_CATALOG_SERVER', 'shorturl.at/enrC3');
  define('HTTPS_CATALOG_SERVER', 'shorturl.at/enrC3');
  define('ENABLE_SSL_CATALOG', 'false');
  define('DIR_FS_DOCUMENT_ROOT', '/var/www/html/stores/AshokProvision/');
  define('DIR_WS_ADMIN', '/stores/AshokProvision/admin/');
  define('DIR_WS_HTTPS_ADMIN', '/stores/AshokProvision/admin/');
  define('DIR_FS_ADMIN', '/var/www/html/stores/AshokProvision/admin/');
  define('DIR_WS_CATALOG', '/stores/AshokProvision/');
  define('DIR_WS_HTTPS_CATALOG', '/stores/AshokProvision/');
  define('DIR_FS_CATALOG', '/var/www/html/stores/AshokProvision/');
  define('DIR_WS_CATALOG_IMAGES', DIR_WS_CATALOG . 'images/');
  define('DIR_WS_CATALOG_LANGUAGES', DIR_WS_CATALOG . 'includes/languages/');
  define('DIR_FS_CATALOG_LANGUAGES', DIR_FS_CATALOG . 'includes/languages/');
  define('DIR_FS_CATALOG_IMAGES', DIR_FS_CATALOG . 'images/');
  define('DIR_FS_CATALOG_MODULES', DIR_FS_CATALOG . 'includes/modules/');
  define('DIR_FS_BACKUP', DIR_FS_ADMIN . 'backups/');
  define('DIR_FS_DOWNLOAD', DIR_FS_CATALOG . 'download/');
  define('DIR_FS_DOWNLOAD_PUBLIC', DIR_FS_CATALOG . 'pub/');
  define('DB_SERVER', '127.0.0.1');
  define('DB_SERVER_USERNAME', 'root');
  define('DB_SERVER_PASSWORD', 'Seamless@123');
  define('DB_DATABASE', 'AshokProvision');
  define('USE_PCONNECT', 'false');
  define('STORE_SESSIONS', 'mysql');
  define('CFG_TIME_ZONE', 'Asia/Kolkata');
}
?>
